services:
  elasticsearch:
    image: elasticsearch:8.8.0
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
  caddy-fileserver:
    image: caddy:2.7.6-alpine
    command: caddy file-server --listen 0.0.0.0:9898 --root /srv/www
    volumes:
      - ./data:/srv/www
    restart: unless-stopped
  caddy:
    image: caddy:2.7.6-alpine
    ports:
      - 127.0.0.1:9999:9999
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    environment:
      - FILESERVER_HOST=caddy-fileserver:9898
      - FRONTEND_HOST=host.docker.internal:5173
      - BACKEND_HOST=host.docker.internal:8000