"""separated address and coordinates into individual fields

Revision ID: 7b63bee3082e
Revises: a504968f8fb4
Create Date: 2024-09-27 15:14:10.888494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7b63bee3082e'
down_revision: Union[str, None] = 'a504968f8fb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('memory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memory.id'], ),
    sa.PrimaryKeyConstraint('name', 'memory_id')
    )
    op.add_column('memory', sa.Column('image_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('memory', sa.Column('long', sa.Numeric(precision=3, scale=6), nullable=False))
    op.add_column('memory', sa.Column('lat', sa.Numeric(precision=3, scale=6), nullable=False))
    op.add_column('memory', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('memory', sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('memory', sa.Column('zip', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('memory', sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('memory', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('memory', sa.Column('audio_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('memory', sa.Column('audio_transcript', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('memory', sa.Column('orc_result', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memory', 'orc_result')
    op.drop_column('memory', 'audio_transcript')
    op.drop_column('memory', 'audio_source')
    op.drop_column('memory', 'address')
    op.drop_column('memory', 'country')
    op.drop_column('memory', 'zip')
    op.drop_column('memory', 'state')
    op.drop_column('memory', 'city')
    op.drop_column('memory', 'lat')
    op.drop_column('memory', 'long')
    op.drop_column('memory', 'image_source')
    op.drop_table('tag')
    # ### end Alembic commands ###
